include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - use_super_parameters
    - only_throw_errors
    - directives_ordering
    - prefer_relative_imports
    - cascade_invocations: false

